### ISSUE TITLE
该版本是可以正常编译使用的吗？编译时是否需要额外参数？

### ISSUE THREAD

**Issue by Crispy256** [Ascend/slurm-atlas-plugin#1]
公司目前有几台昇腾服务器，想组slurm集群，但是开源的版本无法对npu进行调度，8卡机器只能使用一张卡，能否提供下编译及使用配置的相关说明

**Comment by ascendhuawei** [comment]
Hi, Sorry that is repo is already outdated. We will remove it soon, sorry for the confusion.

**Comment by Crispy256** [comment]
那么开源的slurm版本有办法使用昇腾服务器吗

**Comment by blue-U** [comment]
> 那么开源的slurm版本有办法使用昇腾服务器吗

您好，您这边是否有找到其他的版本呢？
